spring:
  security:
    oauth2:
      client:
        registration:
          simulated-auth:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            client-authentication-method: post
            authorization-grant-type: authorization_code
            redirect-uri: ${REDIRECT_URI}
        provider:
          simulated-auth:
            authorization-uri: ${OAUTH_ENDPOINT}
            token-uri: ${OAUTH_ENDPOINT}/token
            user-info-uri: ${OAUTH_ENDPOINT}/userinfo
            userNameAttribute: name
