auth:
  provider:
    client-id: ${PROVIDER_CLIENT_ID}
    client-secret: ${PROVIDER_CLIENT_SECRET}
    redirect-uri: ${PROVIDER_REDIRECT_URI}
    authorization-uri: ${PROVIDER_OAUTH_ENDPOINT}/auth
    scope: openid
    token-uri: ${PROVIDER_OAUTH_ENDPOINT}/token
  service:
    kid: "test-1"
    private-key-path: ${SERVICE_KEY_PATH}
    token-uri: ${SERVICE_OAUTH_ENDPOINT}/token
    client-id: ${SERVICE_CLIENT_ID}

app:
  endpoint: ${ENDPOINT}
