auth:
  provider:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    redirect-uri: ${REDIRECT_URI}
    authorization-uri: ${OAUTH_ENDPOINT}/auth
    scope: openid
    token-uri: ${OAUTH_ENDPOINT}/token
  service:
    kid: "test-1"
    private-key-path: ${SERVICE_KEY_PATH}
    tokenUri: ${SERVICE_OAUTH_ENDPOINT}/token
    clientId: ${SERVICE_CLIENT_ID}

app:
  endpoint: ${ENDPOINT}
